"""
NIST SP 800-171 Rev. 2 — all 110 security requirements.

Numbering note: 800-171 requirements are numbered 3.1.1 - 3.14.7 across 14
families. They are NOT the 800-53 control IDs (AC-2, IA-5, SC-7...). 800-53 is
the source catalog 800-171 was derived from, but an SSP for CMMC must cite the
3.x.x requirement numbers. Anything using AC-2 style IDs in a CMMC deliverable
will be flagged by an assessor.

Revision note: CMMC Level 2 is currently tied to 800-171 Rev. 2. Rev. 3 (May
2024) restructured to a different family and requirement count. Do not mix them.

Each entry: (id, requirement_text, starter_implementation_statement)
The starter statement is a STARTING POINT describing a common, defensible
implementation. It must be edited to describe what the organization actually
does. A statement that does not match reality is worse than a blank field.
"""

FAMILIES = [
    ("3.1",  "AC", "Access Control", 22),
    ("3.2",  "AT", "Awareness and Training", 3),
    ("3.3",  "AU", "Audit and Accountability", 9),
    ("3.4",  "CM", "Configuration Management", 9),
    ("3.5",  "IA", "Identification and Authentication", 11),
    ("3.6",  "IR", "Incident Response", 3),
    ("3.7",  "MA", "Maintenance", 6),
    ("3.8",  "MP", "Media Protection", 9),
    ("3.9",  "PS", "Personnel Security", 2),
    ("3.10", "PE", "Physical Protection", 6),
    ("3.11", "RA", "Risk Assessment", 3),
    ("3.12", "CA", "Security Assessment", 4),
    ("3.13", "SC", "System and Communications Protection", 16),
    ("3.14", "SI", "System and Information Integrity", 7),
]

CONTROLS = [
# --- 3.1 Access Control (22) ------------------------------------------------
("3.1.1", "Limit system access to authorized users, processes acting on behalf of authorized users, and devices (including other systems).",
 "All access to systems in the CUI environment requires a named, individually assigned account. Accounts are created only on approved written request from a manager and are provisioned by [ROLE]. Shared and generic accounts are prohibited. Device access is limited to assets on the approved inventory; unmanaged devices cannot join the network."),
("3.1.2", "Limit system access to the types of transactions and functions that authorized users are permitted to execute.",
 "Access is granted through role-based groups rather than per-user permissions. Each role is documented with the systems, shares, and functions it permits. Users receive only the roles their job requires, approved by their manager and reviewed [QUARTERLY]."),
("3.1.3", "Control the flow of CUI in accordance with approved authorizations.",
 "CUI is confined to the defined system boundary. Firewall rules and share permissions prevent CUI from moving to out-of-scope systems. Egress paths that could carry CUI (email, file sharing, removable media) are restricted to approved, controlled services documented in the SSP."),
("3.1.4", "Separate the duties of individuals to reduce the risk of malevolent activity without collusion.",
 "Security-relevant duties are divided so no single individual can act unchecked. [DESCRIBE THE SPLIT: e.g. the person who approves access requests is not the person who provisions them; the person who administers systems is not the sole reviewer of audit logs.] Where headcount prevents full separation, the compensating review is documented here."),
("3.1.5", "Employ the principle of least privilege, including for specific security functions and privileged accounts.",
 "Users receive the minimum access needed for their role. Administrative rights are granted only to designated personnel and only on the systems they administer. Local administrator rights are removed from standard workstations. Privileged access is reviewed [QUARTERLY] and revoked when no longer required."),
("3.1.6", "Use non-privileged accounts or roles when accessing nonsecurity functions.",
 "Administrators hold two accounts: a standard account for daily work (email, browsing, documents) and a separate privileged account used only for administrative tasks. Privileged accounts are technically prevented from accessing email and the internet."),
("3.1.7", "Prevent non-privileged users from executing privileged functions and capture the execution of such functions in the audit logs.",
 "Privileged functions are restricted to members of the administrative groups; standard users are denied by policy and by configuration. Execution of privileged functions and all privilege-escalation events are logged and forwarded to [LOG SYSTEM] for review."),
("3.1.8", "Limit unsuccessful logon attempts.",
 "Accounts lock after [N] consecutive failed logon attempts within [N] minutes and remain locked for [N] minutes or until an administrator unlocks them. The setting is enforced centrally through [GROUP POLICY / MDM] so it cannot be changed locally."),
("3.1.9", "Provide privacy and security notices consistent with applicable CUI rules.",
 "An approved system use notification banner is displayed at logon on all systems in the CUI environment. The banner states that the system is for authorized use only, that activity is monitored, and that use constitutes consent to monitoring. Banner text is enforced centrally."),
("3.1.10", "Use session lock with pattern-hiding displays to prevent access and viewing of data after a period of inactivity.",
 "Systems lock automatically after [15] minutes of inactivity and display a screen saver that conceals the previous screen contents. Re-authentication is required to resume. The setting is enforced centrally and users cannot disable it. Users are trained to lock manually when stepping away."),
("3.1.11", "Terminate (automatically) a user session after a defined condition.",
 "User sessions terminate automatically after [DEFINED CONDITION: e.g. 30 minutes of inactivity for remote sessions, or at end of the defined maximum session length]. Remote and privileged sessions are terminated on the shorter timer."),
("3.1.12", "Monitor and control remote access sessions.",
 "Remote access is permitted only through the [VPN / approved remote access solution]. All remote sessions are logged with user, source address, and duration, and those logs are reviewed [WEEKLY]. Remote access is enabled only for users with a documented business need."),
("3.1.13", "Employ cryptographic mechanisms to protect the confidentiality of remote access sessions.",
 "All remote access sessions are encrypted using [FIPS-VALIDATED MECHANISM, e.g. TLS 1.2+ / IPsec] as configured in [SOLUTION]. Unencrypted remote access protocols are blocked at the firewall."),
("3.1.14", "Route remote access via managed access control points.",
 "All remote access is routed through a single managed concentrator at [LOCATION/DEVICE]. No system in the CUI environment accepts inbound remote sessions directly; the firewall denies such connections."),
("3.1.15", "Authorize remote execution of privileged commands and remote access to security-relevant information.",
 "Remote execution of privileged commands is limited to named administrators and requires connection through the managed access point with multifactor authentication. Each authorization is documented and reviewed [QUARTERLY]. Remote access to security-relevant information (logs, configurations, security tooling) is restricted to the same group."),
("3.1.16", "Authorize wireless access prior to allowing such connections.",
 "Wireless access is authorized in writing before a device is permitted to connect. Only devices on the approved inventory can join the corporate wireless network; all others are placed on an isolated guest network with no route to the CUI environment."),
("3.1.17", "Protect wireless access using authentication and encryption.",
 "Corporate wireless uses [WPA2-Enterprise / WPA3-Enterprise] with [802.1X] authentication against [IDENTITY PROVIDER] and AES encryption. Pre-shared keys are not used on networks that carry CUI. Legacy protocols (WEP, WPA, TKIP) are disabled."),
("3.1.18", "Control connection of mobile devices.",
 "Mobile devices connect only after enrollment in [MDM SOLUTION], which enforces encryption, screen lock, and remote wipe. Unenrolled devices cannot access CUI. The mobile device inventory is maintained by [ROLE]."),
("3.1.19", "Encrypt CUI on mobile devices and mobile computing platforms.",
 "Full-disk encryption is enforced on all laptops and mobile devices via [BITLOCKER / FILEVAULT / MDM POLICY]. Encryption status is verified centrally, and devices reporting as unencrypted are blocked from the network until remediated."),
("3.1.20", "Verify and control/limit connections to and use of external systems.",
 "Use of external systems (personal devices, third-party cloud services, partner networks) to store or process CUI is prohibited unless explicitly approved and documented. Approved external connections are listed in the SSP with the terms that govern them."),
("3.1.21", "Limit use of portable storage devices on external systems.",
 "Organization-owned portable storage containing CUI may not be used on external systems. USB mass storage is [BLOCKED BY DEFAULT] through [GROUP POLICY / ENDPOINT CONTROL], with exceptions granted in writing and recorded."),
("3.1.22", "Control CUI posted or processed on publicly accessible systems.",
 "CUI is prohibited on public-facing systems. Content destined for the public website or social media is reviewed and approved by [ROLE] before publication. Publicly accessible systems are reviewed [QUARTERLY] to confirm no CUI is present."),
# --- 3.2 Awareness and Training (3) -----------------------------------------
("3.2.1", "Ensure that managers, systems administrators, and users of organizational systems are made aware of the security risks associated with their activities and of the applicable policies, standards, and procedures related to the security of those systems.",
 "All personnel complete security awareness training at hire and annually thereafter. Training covers CUI handling, phishing, password practices, physical security, and incident reporting. Completion is tracked by [ROLE] and records are retained for [3] years."),
("3.2.2", "Ensure that personnel are trained to carry out their assigned information security-related duties and responsibilities.",
 "Personnel with security responsibilities (administrators, incident responders, the security officer) receive role-specific training beyond general awareness, appropriate to their duties. Training is documented and refreshed annually."),
("3.2.3", "Provide security awareness training on recognizing and reporting potential indicators of insider threat.",
 "Annual awareness training includes a module on insider threat indicators and the mechanism for reporting concerns. Reporting channels are stated in the training and do not require reporting through the individual's own management chain."),
]

CONTROLS += [
# --- 3.3 Audit and Accountability (9) ---------------------------------------
("3.3.1", "Create and retain system audit logs and records to the extent needed to enable the monitoring, analysis, investigation, and reporting of unlawful or unauthorized system activity.",
 "Audit logging is enabled on all systems in the CUI environment. Logged events include logon/logoff, privilege use, account management, object access to CUI locations, policy changes, and system events. Logs are forwarded to [LOG SYSTEM] and retained for [90 DAYS ONLINE / 1 YEAR ARCHIVED]."),
("3.3.2", "Ensure that the actions of individual system users can be uniquely traced to those users so they can be held accountable for their actions.",
 "Every user has a unique individual account; shared accounts are prohibited. Administrators use named privileged accounts rather than built-in shared accounts. Audit records capture the acting user ID, so any action can be traced to one individual."),
("3.3.3", "Review and update logged events.",
 "The list of logged event types is reviewed [ANNUALLY] and after any significant system change or incident, to confirm it still captures what is needed for investigation. Changes are approved by [ROLE] and recorded."),
("3.3.4", "Alert in the event of an audit logging process failure.",
 "[LOG SYSTEM] generates an alert to [ROLE] when a log source stops reporting, when log storage approaches capacity, or when the logging service fails. Alerts are actioned within [DEFINED TIME]."),
("3.3.5", "Correlate audit record review, analysis, and reporting processes for investigation and response to indications of unlawful, unauthorized, suspicious, or unusual activity.",
 "Logs from endpoints, servers, network devices, and cloud services are centralized in [LOG SYSTEM], which correlates events across sources. Correlated alerts are reviewed [DAILY/WEEKLY] by [ROLE] and escalated to the incident response process when warranted."),
("3.3.6", "Provide audit record reduction and report generation to support on-demand analysis and reporting.",
 "[LOG SYSTEM] provides search, filtering, and reporting across retained audit records, allowing on-demand analysis without altering the original records."),
("3.3.7", "Provide a system capability that compares and synchronizes internal system clocks with an authoritative source to generate time stamps for audit records.",
 "All systems synchronize time via NTP against [AUTHORITATIVE SOURCE, e.g. the domain controller, which syncs to time.nist.gov]. Time stamps in audit records use [UTC]. Synchronization failures are alerted."),
("3.3.8", "Protect audit information and audit logging tools from unauthorized access, modification, and deletion.",
 "Audit records are forwarded off the originating host to [LOG SYSTEM], where access is restricted to [ROLE] and records are write-once for the retention period. Local log permissions prevent modification by standard users."),
("3.3.9", "Limit management of audit logging functionality to a subset of privileged users.",
 "Only members of [SECURITY ADMIN GROUP] can configure logging, change retention, or manage the log platform. General system administrators can read logs but cannot alter logging configuration or delete records."),
# --- 3.4 Configuration Management (9) ---------------------------------------
("3.4.1", "Establish and maintain baseline configurations and inventories of organizational systems (including hardware, software, firmware, and documentation) throughout the respective system development life cycles.",
 "Documented baseline configurations exist for each system type in the CUI environment (workstation, server, network device). A hardware and software inventory is maintained in [INVENTORY TOOL/REGISTER] and reconciled [QUARTERLY]. Baselines are versioned and updated through the change process."),
("3.4.2", "Establish and enforce security configuration settings for information technology products employed in organizational systems.",
 "Security settings are derived from [CIS BENCHMARKS / DISA STIGs] and enforced centrally via [GROUP POLICY / MDM / CONFIGURATION MANAGEMENT]. Deviations require documented approval. Compliance with the baseline is verified [QUARTERLY]."),
("3.4.3", "Track, review, approve or disapprove, and log changes to organizational systems.",
 "Changes to systems in the CUI environment are raised as change requests, reviewed and approved by [ROLE/CHANGE BOARD] before implementation, and recorded in [CHANGE LOG] with requester, approver, date, and description. Emergency changes are documented retroactively within [DEFINED TIME]."),
("3.4.4", "Analyze the security impact of changes prior to implementation.",
 "Each change request includes a security impact assessment covering the effect on the system boundary, CUI flow, and existing security requirements. Changes with material security impact are tested in [TEST ENVIRONMENT] before production."),
("3.4.5", "Define, document, approve, and enforce physical and logical access restrictions associated with changes to organizational systems.",
 "Only authorized administrators may implement approved changes. Logical restrictions are enforced through privileged group membership; physical restrictions through controlled access to server and network equipment areas. Change implementation is logged."),
("3.4.6", "Employ the principle of least functionality by configuring organizational systems to provide only essential capabilities.",
 "Systems are built from a hardened baseline that installs only the roles, features, and applications required for their function. Unnecessary services, roles, and default applications are removed or disabled as part of the build."),
("3.4.7", "Restrict, disable, or prevent the use of nonessential programs, functions, ports, protocols, and services.",
 "A list of permitted programs, ports, protocols, and services is documented and enforced. Host firewalls deny inbound traffic by default. Nonessential services are disabled in the baseline, and the permitted list is reviewed [ANNUALLY]."),
("3.4.8", "Apply deny-by-exception (blacklisting) policy to prevent the use of unauthorized software or deny-all, permit-by-exception (whitelisting) policy to allow the execution of authorized software.",
 "[APPLICATION ALLOWLISTING via AppLocker / WDAC / equivalent] is enforced on systems in the CUI environment, permitting execution only of approved software. The approved software list is maintained by [ROLE] and changes follow the change process."),
("3.4.9", "Control and monitor user-installed software.",
 "Standard users cannot install software; local administrator rights are removed. Software installation requests are approved by [ROLE] and installed by administrators. Installed software is monitored through [INVENTORY TOOL] and unauthorized software is investigated and removed."),
# --- 3.5 Identification and Authentication (11) -----------------------------
("3.5.1", "Identify system users, processes acting on behalf of users, and devices.",
 "Each user is assigned a unique identifier in [IDENTITY PROVIDER]. Service and process accounts are individually named, documented, and tied to a responsible owner. Devices are identified by hostname and asset tag and recorded on the inventory."),
("3.5.2", "Authenticate (or verify) the identities of users, processes, or devices, as a prerequisite to allowing access to organizational systems.",
 "All users authenticate against [IDENTITY PROVIDER] before access is granted. Service accounts authenticate using managed credentials. Devices authenticate to the network using [802.1X / certificate / domain membership]."),
("3.5.3", "Use multifactor authentication for local and network access to privileged accounts and for network access to non-privileged accounts.",
 "Multifactor authentication is enforced for all privileged accounts (local and network) and for all network access by non-privileged accounts, using [MFA SOLUTION] with [FACTORS]. MFA cannot be bypassed; exceptions are not permitted."),
("3.5.4", "Employ replay-resistant authentication mechanisms for network access to privileged and non-privileged accounts.",
 "Network authentication uses replay-resistant mechanisms: [KERBEROS / TLS-PROTECTED AUTHENTICATION / TIME-BASED OR CHALLENGE-RESPONSE MFA]. Legacy protocols vulnerable to replay (LM, NTLMv1) are disabled."),
("3.5.5", "Prevent reuse of identifiers for a defined period.",
 "User identifiers are never reused. Identifiers of departed personnel are retained in a disabled state and are not reissued to new users, preserving the audit trail."),
("3.5.6", "Disable identifiers after a defined period of inactivity.",
 "Accounts inactive for [45] days are automatically disabled. A [MONTHLY] report of inactive accounts is reviewed by [ROLE], and accounts disabled for [90] days without justification are removed."),
("3.5.7", "Enforce a minimum password complexity and change of characters when new passwords are created.",
 "Password policy enforces a minimum length of [14] characters and complexity requirements, enforced centrally through [GROUP POLICY / IDENTITY PROVIDER]. New passwords must differ from the previous password by more than a single character."),
("3.5.8", "Prohibit password reuse for a specified number of generations.",
 "Password history is enforced at [24] generations, preventing reuse of recent passwords. The setting is enforced centrally and cannot be overridden locally."),
("3.5.9", "Allow temporary password use for system logons with an immediate change to a permanent password.",
 "Temporary passwords issued for new accounts or resets are unique per user, communicated through a verified channel, and flagged to require change at first logon."),
("3.5.10", "Store and transmit only cryptographically-protected passwords.",
 "Passwords are stored only as salted cryptographic hashes by [IDENTITY PROVIDER] and are never stored in clear text. Authentication traffic is encrypted in transit. Storage of passwords in scripts, documents, or configuration files is prohibited; secrets are held in [PASSWORD MANAGER / SECRETS STORE]."),
("3.5.11", "Obscure feedback of authentication information.",
 "Password entry is masked on all interfaces. Authentication failure messages do not reveal whether the username or the password was incorrect."),
# --- 3.6 Incident Response (3) ----------------------------------------------
("3.6.1", "Establish an operational incident-handling capability for organizational systems that includes preparation, detection, analysis, containment, recovery, and user response activities.",
 "A documented Incident Response Plan defines the phases of incident handling, the response team and their roles, severity definitions, and escalation paths. Contact details are maintained and the plan is available offline. Users are trained to report suspected incidents to [CHANNEL]."),
("3.6.2", "Track, document, and report incidents to designated officials and/or authorities both internal and external to the organization.",
 "Incidents are recorded in [TRACKING SYSTEM] with timeline, actions, and outcome, and reported to [DESIGNATED OFFICIAL]. Cyber incidents affecting covered defense information are reported to DoD via https://dibnet.dod.mil within 72 hours as required by DFARS 252.204-7012."),
("3.6.3", "Test the organizational incident response capability.",
 "The incident response capability is tested at least [ANNUALLY] through a tabletop exercise or simulated incident. Results, gaps, and corrective actions are documented and folded back into the plan."),
]

CONTROLS += [
# --- 3.7 Maintenance (6) ----------------------------------------------------
("3.7.1", "Perform maintenance on organizational systems.",
 "Scheduled maintenance (patching, firmware updates, hardware servicing) is performed on a documented cadence by authorized personnel and recorded in [MAINTENANCE LOG] with date, system, activity, and technician."),
("3.7.2", "Provide controls on the tools, techniques, mechanisms, and personnel used to conduct system maintenance.",
 "Maintenance is performed only by authorized personnel using approved tools. Diagnostic and maintenance tools are inventoried and controlled; tools brought in by third parties are inspected and approved before use."),
("3.7.3", "Ensure equipment removed for off-site maintenance is sanitized of any CUI.",
 "Equipment leaving the facility for maintenance or repair is sanitized of CUI beforehand using [METHOD], or the storage media is removed and retained. Sanitization is documented and verified by [ROLE] prior to release."),
("3.7.4", "Check media containing diagnostic and test programs for malicious code before the media are used in organizational systems.",
 "Any media containing diagnostic or test programs is scanned for malicious code on an isolated system before use in the CUI environment. Media that cannot be scanned is not permitted."),
("3.7.5", "Require multifactor authentication to establish nonlocal maintenance sessions via external network connections and terminate such connections when nonlocal maintenance is complete.",
 "Remote maintenance sessions require multifactor authentication through the managed remote access solution. Sessions are monitored while active and terminated immediately on completion; the remote access account is disabled when not in use."),
("3.7.6", "Supervise the maintenance activities of maintenance personnel without required access authorization.",
 "Maintenance personnel without authorization to access CUI are escorted and supervised by an authorized employee for the duration of their work. Supervision is recorded in the maintenance log."),
# --- 3.8 Media Protection (9) -----------------------------------------------
("3.8.1", "Protect (i.e., physically control and securely store) system media containing CUI, both paper and digital.",
 "Digital and paper media containing CUI are stored in locked containers or controlled rooms accessible only to authorized personnel. Media is not left unattended in unsecured areas; a clean-desk practice applies to CUI in hard copy."),
("3.8.2", "Limit access to CUI on system media to authorized users.",
 "Access to media containing CUI is limited to users with a documented need. Digital media access is enforced by file permissions; physical media is held in controlled storage with access limited to [ROLE]."),
("3.8.3", "Sanitize or destroy system media containing CUI before disposal or release for reuse.",
 "Media containing CUI is sanitized or destroyed before disposal or reuse using methods consistent with NIST SP 800-88. Paper is cross-cut shredded. Destruction is recorded in [DISPOSAL LOG] with date, media, method, and person responsible."),
("3.8.4", "Mark media with necessary CUI markings and distribution limitations.",
 "Media containing CUI is marked with the CUI designation and any applicable distribution limitations, in line with 32 CFR Part 2002 and the applicable contract. Marking is covered in annual awareness training."),
("3.8.5", "Control access to media containing CUI and maintain accountability for media during transport outside of controlled areas.",
 "Media containing CUI transported outside controlled areas is logged out and in, is encrypted or otherwise protected, and remains in the custody of an authorized individual or an approved courier with tracking."),
("3.8.6", "Implement cryptographic mechanisms to protect the confidentiality of CUI stored on digital media during transport unless otherwise protected by alternative physical safeguards.",
 "Digital media containing CUI is encrypted with [FIPS-VALIDATED MECHANISM] before leaving a controlled area. Unencrypted media may only be transported under the alternative physical safeguards documented here."),
("3.8.7", "Control the use of removable media on system components.",
 "Removable media use is [BLOCKED BY DEFAULT] through [ENDPOINT CONTROL]. Exceptions require written approval, are limited to organization-issued encrypted media, and are recorded."),
("3.8.8", "Prohibit the use of portable storage devices when such devices have no identifiable owner.",
 "Portable storage devices without an identifiable owner are prohibited. Endpoint controls block unknown devices, and users are trained never to connect found or unattributed media."),
("3.8.9", "Protect the confidentiality of backup CUI at storage locations.",
 "Backups containing CUI are encrypted at rest using [FIPS-VALIDATED MECHANISM] and stored at [LOCATION] with access restricted to [ROLE]. Restoration is tested [ANNUALLY] and offsite backup providers are covered by an agreement addressing CUI protection."),
# --- 3.9 Personnel Security (2) ---------------------------------------------
("3.9.1", "Screen individuals prior to authorizing access to organizational systems containing CUI.",
 "Personnel are screened before being granted access to systems containing CUI, in accordance with [SCREENING STANDARD] and any contract-specific requirements. Screening completion is recorded by [HR/ROLE] before account provisioning."),
("3.9.2", "Ensure that organizational systems containing CUI are protected during and after personnel actions such as terminations and transfers.",
 "A documented offboarding process disables all accounts, revokes physical access, and recovers organization-issued equipment and media within [SAME DAY / DEFINED TIME] of separation. Transfers trigger an access review so permissions match the new role and prior access is removed."),
# --- 3.10 Physical Protection (6) -------------------------------------------
("3.10.1", "Limit physical access to organizational systems, equipment, and the respective operating environments to authorized individuals.",
 "Physical access to facilities and to areas housing systems that process or store CUI is limited to authorized personnel through [ACCESS CONTROL MECHANISM]. Server and network equipment is in a locked room or locked rack with access limited to [ROLE]."),
("3.10.2", "Protect and monitor the physical facility and support infrastructure for organizational systems.",
 "The facility and supporting infrastructure are protected by [LOCKS / ALARM / CAMERAS] and monitored during and outside business hours. Alarm and camera events are reviewed following any suspected physical security incident."),
("3.10.3", "Escort visitors and monitor visitor activity.",
 "Visitors sign in, are issued a visitor badge, and are escorted by an employee at all times while in areas where CUI is processed or stored. Visitors are never left unattended in those areas."),
("3.10.4", "Maintain audit logs of physical access.",
 "Physical access is logged through [BADGE SYSTEM / VISITOR LOG] recording name, date, time in and out, and purpose. Logs are retained for [1 YEAR] and reviewed by [ROLE] on a [MONTHLY] basis or following an incident."),
("3.10.5", "Control and manage physical access devices.",
 "Keys, badges, and other physical access devices are inventoried and issued to named individuals by [ROLE]. Devices are recovered at separation, and locks or codes are changed when a device is lost or unrecoverable. The inventory is reconciled [ANNUALLY]."),
("3.10.6", "Enforce safeguarding measures for CUI at alternate work sites.",
 "Remote and alternate work sites are covered by a documented telework standard requiring encrypted organization-issued devices, VPN for access to CUI, a private workspace, locked storage for hard-copy CUI, and prohibition of shared or public networks without VPN."),
# --- 3.11 Risk Assessment (3) -----------------------------------------------
("3.11.1", "Periodically assess the risk to organizational operations, organizational assets, and individuals, resulting from the operation of organizational systems and the associated processing, storage, or transmission of CUI.",
 "A documented risk assessment is performed [ANNUALLY] and after significant change, identifying threats, vulnerabilities, likelihood, and impact to CUI. Results are recorded in the risk register, briefed to leadership, and drive POA&M priorities."),
("3.11.2", "Scan for vulnerabilities in organizational systems and applications periodically and when new vulnerabilities affecting those systems and applications are identified.",
 "Authenticated vulnerability scans of all systems in the CUI environment are performed [MONTHLY] using [SCANNER], and out-of-cycle when a significant vulnerability is announced. Scan reports are retained and reviewed by [ROLE]."),
("3.11.3", "Remediate vulnerabilities in accordance with risk assessments.",
 "Vulnerabilities are remediated on a risk-based schedule: [CRITICAL within 15 days, HIGH within 30, MEDIUM within 90]. Remediation is tracked to closure and verified by rescan. Vulnerabilities that cannot be remediated in the window are risk-accepted in writing by [ROLE] and tracked on the POA&M."),
# --- 3.12 Security Assessment (4) -------------------------------------------
("3.12.1", "Periodically assess the security controls in organizational systems to determine if the controls are effective in their application.",
 "Security requirements are assessed at least [ANNUALLY] against the NIST SP 800-171 DoD Assessment Methodology. Assessment results, including the score and supporting evidence, are documented and retained."),
("3.12.2", "Develop and implement plans of action designed to correct deficiencies and reduce or eliminate vulnerabilities in organizational systems.",
 "Every deficiency identified in assessment is recorded on the Plan of Action and Milestones with a named owner, remediation plan, and milestone date. The POA&M is reviewed [MONTHLY] and items are closed only with evidence."),
("3.12.3", "Monitor security controls on an ongoing basis to ensure the continued effectiveness of the controls.",
 "Continuous monitoring includes [MONTHLY] vulnerability scanning, [WEEKLY] log review, [QUARTERLY] access reviews, and [QUARTERLY] baseline configuration checks. Results are recorded and deviations raised through the POA&M."),
("3.12.4", "Develop, document, and periodically update system security plans that describe system boundaries, system environments of operation, how security requirements are implemented, and the relationships with or connections to other systems.",
 "This System Security Plan documents the system boundary, environment of operation, implementation of each of the 110 security requirements, and connections to external systems. It is reviewed and updated [ANNUALLY] and after significant change, under version control with a documented revision history."),
# --- 3.13 System and Communications Protection (16) -------------------------
("3.13.1", "Monitor, control, and protect communications at the external boundaries and key internal boundaries of organizational systems.",
 "Communications are controlled at the external boundary by [FIREWALL] with a deny-by-default ruleset, and at key internal boundaries by [VLAN SEGMENTATION / INTERNAL FIREWALL] separating the CUI environment from the rest of the network. Boundary traffic is logged and reviewed."),
("3.13.2", "Employ architectural designs, software development techniques, and systems engineering principles that promote effective information security within organizational systems.",
 "Security is addressed in system design decisions: the CUI environment is segmented, least functionality and least privilege are applied at build time, and changes are subject to security impact analysis. [IF SOFTWARE IS DEVELOPED: secure development practices and code review apply.]"),
("3.13.3", "Separate user functionality from system management functionality.",
 "Administrative interfaces are separated from user-facing functionality. Management interfaces are reachable only from [ADMIN NETWORK/VLAN] by privileged accounts and are not exposed to general users or the internet."),
("3.13.4", "Prevent unauthorized and unintended information transfer via shared system resources.",
 "Systems are configured to clear shared resources between uses, using operating system defaults for memory and storage object reuse. Temporary files and virtual memory are protected by full-disk encryption, and shared storage uses per-user permissions."),
("3.13.5", "Implement subnetworks for publicly accessible system components that are physically or logically separated from internal networks.",
 "Publicly accessible components are placed in a DMZ separated from internal networks by firewall rules that deny direct inbound traffic to internal systems. No CUI resides on systems in the DMZ."),
("3.13.6", "Deny network communications traffic by default and allow network communications traffic by exception.",
 "Perimeter and host firewalls deny all traffic by default; only explicitly approved flows are permitted. The ruleset is documented with business justification per rule and reviewed [ANNUALLY] to remove rules no longer needed."),
("3.13.7", "Prevent remote devices from simultaneously establishing non-remote connections with organizational systems and communicating via some other connection to resources in external networks (split tunneling).",
 "Split tunneling is disabled on the VPN client; all traffic from connected remote devices is routed through the organization's network and egress controls while the tunnel is established. The setting is enforced by policy and cannot be changed by the user."),
("3.13.8", "Implement cryptographic mechanisms to prevent unauthorized disclosure of CUI during transmission unless otherwise protected by alternative physical safeguards.",
 "CUI in transit is protected with [FIPS-VALIDATED CRYPTOGRAPHY]: TLS 1.2 or higher for web and email, encrypted VPN for remote access, and SFTP or equivalent for file transfer. Unencrypted transmission of CUI is prohibited."),
("3.13.9", "Terminate network connections associated with communications sessions at the end of the sessions or after a defined period of inactivity.",
 "Network sessions are terminated at session end or after [DEFINED PERIOD] of inactivity. VPN and remote sessions disconnect after [30] minutes idle, enforced by the concentrator rather than the client."),
("3.13.10", "Establish and manage cryptographic keys for cryptography employed in organizational systems.",
 "Cryptographic keys and certificates are generated, distributed, stored, rotated, and revoked under a documented key management practice. Keys are held in [KEY STORE / TPM / MANAGED SERVICE] with access limited to [ROLE]. Certificate expiry is monitored."),
("3.13.11", "Employ FIPS-validated cryptography when used to protect the confidentiality of CUI.",
 "Cryptographic modules used to protect CUI are FIPS 140-2 or 140-3 validated. [LIST MODULES AND CMVP CERTIFICATE NUMBERS.] FIPS mode is enabled where the platform requires it to operate in a validated configuration."),
("3.13.12", "Prohibit remote activation of collaborative computing devices and provide indication of devices in use to users present at the device.",
 "Remote activation of cameras and microphones is disabled by policy. Collaboration software indicates clearly when a camera or microphone is active, and users are trained on physical camera covers and mute practice in areas where CUI is discussed."),
("3.13.13", "Control and monitor the use of mobile code.",
 "Mobile code (JavaScript, ActiveX, Java applets, macros) is controlled through browser and application policy. Office macros from the internet are blocked by default; exceptions require approval and are signed."),
("3.13.14", "Control and monitor the use of Voice over Internet Protocol (VoIP) technologies.",
 "VoIP use is limited to the approved [SOLUTION], configured with encryption for signalling and media, placed on a segmented VLAN, and monitored. Unapproved VoIP applications are blocked."),
("3.13.15", "Protect the authenticity of communications sessions.",
 "Session authenticity is protected using TLS with server certificate validation, mutual authentication where supported, and session tokens that are invalidated at logout. Downgrade to unauthenticated protocols is blocked."),
("3.13.16", "Protect the confidentiality of CUI at rest.",
 "CUI at rest is protected by full-disk encryption on endpoints and servers, and by [SERVICE-SIDE ENCRYPTION] in approved cloud storage, using FIPS-validated mechanisms. Encryption status is verified centrally."),
# --- 3.14 System and Information Integrity (7) ------------------------------
("3.14.1", "Identify, report, and correct system flaws in a timely manner.",
 "System flaws are identified through vendor advisories, vulnerability scanning, and monitoring. Patches are applied on a risk-based schedule: [CRITICAL within 15 days, HIGH within 30, others within 90]. Patch status is tracked and exceptions are recorded on the POA&M."),
("3.14.2", "Provide protection from malicious code at designated locations within organizational systems.",
 "[ENDPOINT PROTECTION] is deployed on all workstations and servers in the CUI environment, with real-time protection enabled and centrally managed. Email is filtered for malicious attachments and links at the gateway. Coverage is verified centrally."),
("3.14.3", "Monitor system security alerts and advisories and take action in response.",
 "[ROLE] monitors security advisories from CISA, vendors, and [OTHER SOURCES]. Relevant advisories are assessed for applicability, and action is taken through the patch or change process within [DEFINED TIME]. Assessment and action are recorded."),
("3.14.4", "Update malicious code protection mechanisms when new releases are available.",
 "Malicious code protection signatures and engines update automatically at least [DAILY]. The management console reports update status, and endpoints failing to update are investigated."),
("3.14.5", "Perform periodic scans of organizational systems and real-time scans of files from external sources as files are downloaded, opened, or executed.",
 "Real-time scanning is enabled on all endpoints for files downloaded, opened, or executed. Full system scans run [WEEKLY]. Scan results and detections are reported centrally and actioned by [ROLE]."),
("3.14.6", "Monitor organizational systems, including inbound and outbound communications traffic, to detect attacks and indicators of potential attacks.",
 "Inbound and outbound traffic is monitored at the boundary by [FIREWALL/IDS], and endpoint telemetry is collected by [EDR]. Events are forwarded to [LOG SYSTEM] and reviewed [DAILY/WEEKLY]; detections are escalated to the incident response process."),
("3.14.7", "Identify unauthorized use of organizational systems.",
 "Unauthorized use is identified through review of authentication logs, alerting on anomalous logons (unusual hours, locations, or volumes), and periodic access reviews. Suspected unauthorized use is handled as an incident."),
]
